# syntax=docker/dockerfile:1.9

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS builder
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=builder /app/bin/Release/net8.0/publish ./
RUN find .
ENTRYPOINT ["/app/Quotes"]
